package proyecto2ps19;


import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ronald Macal
 */
public class frmAutomoviles extends javax.swing.JFrame {
    DefaultTableModel mod=new DefaultTableModel();
    public static int autoporcliente=0;
    public static String[][] Automoviles=new String[5][5];
    public static boolean desdecliente=false;
    public static String idcliente="";
    /**
     * Creates new form frmAutomoviles
     */
    public frmAutomoviles() {
        initComponents();
        String[] encabezado={"ID Cliente","Placa","Marca","Modelo"};
        mod.setColumnIdentifiers(encabezado);
        tblAutos.setModel(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        lblImgAuto = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JTextField();
        cmbAutos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutos = new javax.swing.JTable();
        pnImagen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Automoviles");

        btnCerrar.setBackground(new java.awt.Color(0, 0, 51));
        btnCerrar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Regresar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMostrar.setBackground(new java.awt.Color(0, 0, 51));
        btnMostrar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        lblImgAuto.setBackground(new java.awt.Color(255, 255, 255));
        lblImgAuto.setForeground(new java.awt.Color(255, 255, 255));

        cmbAutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacio" }));
        cmbAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAutosActionPerformed(evt);
            }
        });

        tblAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAutos);

        javax.swing.GroupLayout pnImagenLayout = new javax.swing.GroupLayout(pnImagen);
        pnImagen.setLayout(pnImagenLayout);
        pnImagenLayout.setHorizontalGroup(
            pnImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
        pnImagenLayout.setVerticalGroup(
            pnImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMostrar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImgAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(pnImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCerrar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cmbAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        if(desdecliente==true){
            frmCliente clie=new frmCliente();
            clie.setVisible(true);
            this.dispose();
        }else{
            frmClientes inicio=new frmClientes();
            inicio.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if(desdecliente==true){
            txtIDCliente.setText(idcliente);
            String datos=Proyecto2PS19.automoviles.mostrarAutos(idcliente);
            try {
                String[] autos=datos.split("-");
                String aux;
                cmbAutos.removeAllItems();
                txtIDCliente.setText(autos[0]);
                aux=autos[1];
                String[] cantidadautos=aux.split(";");
                for (int i = 0; i < cantidadautos.length; i++) {
                    aux=cantidadautos[i];
                    String[] data=aux.split(",");
                    Automoviles[i][0]=idcliente;
                    Automoviles[i][1]=data[0];
                    Automoviles[i][2]=data[1];
                    Automoviles[i][3]=data[2];
                    Automoviles[i][4]=data[3];
                    autoporcliente++;
                    cmbAutos.addItem(Automoviles[i][2]+" "+Automoviles[i][3]);
                }
            } catch (Exception e) {
            }
        
        }else{
            try {
            String id=JOptionPane.showInputDialog(null, "Ingrese el ID del cliente para ver sus autos: ");
            String datos=Proyecto2PS19.automoviles.mostrarAutos(id);
            if(datos==""){
                JOptionPane.showMessageDialog(null, "No existe el ID del cliente que ingresó.");
            }else{
                String[] autos=datos.split("-");
                String aux;
                cmbAutos.removeAllItems();
                txtIDCliente.setText(autos[0]);
                aux=autos[1];
                String[] cantidadautos=aux.split(";");
                for (int i = 0; i < cantidadautos.length; i++) {
                    aux=cantidadautos[i];
                    String[] data=aux.split(",");
                    Automoviles[i][0]=id;
                    Automoviles[i][1]=data[0];
                    Automoviles[i][2]=data[1];
                    Automoviles[i][3]=data[2];
                    Automoviles[i][4]=data[3];
                    autoporcliente++;
                    cmbAutos.addItem(Automoviles[i][2]+" "+Automoviles[i][3]);
                    
                }
            }
            } catch (Exception e) {
            } 
        } 
    }//GEN-LAST:event_btnMostrarActionPerformed

    public void mostrarimagen(String ruta){
        ImageIcon Auto=new ImageIcon(getClass().getResource(ruta));
        ImageIcon icono=new ImageIcon(Auto.getImage().getScaledInstance(lblImgAuto.getWidth(), lblImgAuto.getHeight(), Image.SCALE_DEFAULT));
        lblImgAuto.setIcon(icono);
    }
    
    private void cmbAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutosActionPerformed
        mod.setNumRows(0);
        String seleccion=(String) cmbAutos.getSelectedItem();
        if(seleccion!=null){
            //Hacer la ruta de la imagen
            for (int i = 0; i < autoporcliente; i++) {
                if(seleccion.equals(Automoviles[i][2]+" "+Automoviles[i][3])){
                    String[] tabla={Automoviles[i][0],Automoviles[i][1],Automoviles[i][2],Automoviles[i][3]};
                    mod.addRow(tabla);
                    mostrarimagen(Automoviles[i][4]);
                    
                }
            }
        }
    }//GEN-LAST:event_cmbAutosActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAutomoviles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> cmbAutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImgAuto;
    private javax.swing.JPanel pnImagen;
    private javax.swing.JTable tblAutos;
    private javax.swing.JTextField txtIDCliente;
    // End of variables declaration//GEN-END:variables
}
